select
BDCODEMP,
BDNOMEMP AS BDNOME,
IIF(BDSITEMP = 'TRUE', 'SIM' ,'') AS INATIVA
from TEMPRESAS_ref AS REF
where
BDREFEMP = (SELECT MAX(BDREFEMP) FROM TEMPRESAS_ref WHERE REF.BDCODEMP = BDCODEMP GROUP BY BDCODEMP)
and BDSITEMP <> 'TRUE'
ORDER BY BDCODEMP