select
 BDCODEMP,
 BDCODENQFED,
 BDREFEMP,
 BDFORMATRIBUTACAO
from TENQFED AS REF
where
BDREFEMP = (SELECT MAX(BDREFEMP) FROM TENQFED WHERE REF.BDCODEMP = BDCODEMP GROUP BY BDCODEMP)
GROUP BY BDCODEMP, BDREFEMP, BDCODENQFED, BDFORMATRIBUTACAO